version: "1"
services:
  healthcare-backend:
    type: web-service
    build:
      context: /backend
      dockerfile: /backend/Dockerfile
    ports:
      - port: 8000
        http: /api/*
    env:
      - key: OPENROUTER_API_KEY
        value: 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

  healthcare-frontend:
    type: web-service
    build:
      context: /frontend
      dockerfile: /frontend/Dockerfile
    ports:
      - port: 3000
        http: /*
    env:
      - key: API_URL
        value: ${HEALTHCARE_BACKEND_URL}  # Auto-linked to backend