version: "1"
services:
  healthcare-backend:
    type: web-service
    build:
      context: /backend
      dockerfile: /backend/Dockerfile
    ports:
      - port: 8000
        http: /api/*
    env:
      - key: OPENROUTER_API_KEY
        value: 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

  healthcare-frontend:
    type: web-service
    build:
      context: /frontend
      dockerfile: /frontend/Dockerfile
    ports:
      - port: 3000
        http: /*
    env:
      - key: API_URL
        value: ${HEALTHCARE_BACKEND_URL}  # Auto-linked to backend